### ISSUE TITLE
`time_ns` not in Python 3.6

### ISSUE THREAD

**Issue by julian-t** [CCExtractor/vardbg#4]
The main README says that Python 3.6 or later is required, but the code requires `time.time_ns()`. AFAIK this was introduced in 3.7.

**Comment by cfsmp3** [comment]
https://github.com/CCExtractor/vardbg/issues/1

**Comment by kdrag0n** [comment]
Fixed in v0.11.7. The main profiler case was fixed in #1 but the JSON writer's usage of `time.time_ns()` was missed.
